project:
  type: book
  output-dir: "../docs"

book:
  title: "Deep Learning Book"
  author: "Abhirath Sangala"
  page-navigation: true
  chapters:
    - index.qmd
    - part: Graph Neural Networks
      chatpers:
        - gnn-mpnn.qmd
    - part: Notes related to implementation
      chapters:
        - pytorch-geometric.qmd
        - tutorial-1.ipynb
        - tutorial-2.ipynb
        - tutorial-3.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub: 
    cover-image: cover.png
  



